version: '3.3'
networks:
  default:
    external:
      
services:
  jenkins:
    #image: 'jenkins/jenkins:lts'
    image: 'jenkins/jenkins:2.164.1-alpine'
    user: root # 以root方式运行，不以root运行安装其他服务会没权限还有其他方式可以用
    ports:
        - '8999:8080'
        - '50000:50000'
    volumes:
        - /opt/jenkins:/var/jenkins_home
        - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    restart: always 
    networks:
        - default

#    links:
#        - slave-java
#slave-java:
#    image: 'registry.cn-beijing.aliyuncs.com/qinyujia-test/jenkins-slave-dind-java-maven'
#    restart: always 
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    ports:
        - '8997:8443'
        - '8998:80'
        - '8022:22'
    volumes:
        - /opt/gitlab/config:/etc/gitlab
        - /opt/gitlab/logs:/var/log/gitlab
        - /opt/gitlab/data:/var/opt/gitlab
    privileged: true
    restart: always
    networks:
        - default
networks:
  default:
    driver: 'bridge' 
